### ISSUE TITLE
how to pass options?

### ISSUE THREAD

**Issue by delia-curiel** [approached/laravel-image-optimizer#1]
Hi, I need to configure the optimizer to use the jpegoptim  –max option ...... how can I accomplish this?  Is it possible?

**Comment by approached** [comment]
Hi,

this feature is now not possible. But in the next time i want develop a new package with more dynamic image handling (by passing options on image url).

If you want this feature, feel free to contribute this package. :)

**Comment by delia-curiel** [comment]
ok, thanks!

**Comment by approached** [comment]
Hi,

i updated this module, with a better workflow. Now you can pass your options.

https://github.com/approached/laravel-image-optimizer/tree/2.0.0
