### ISSUE TITLE
File extension capitalized 

### ISSUE THREAD

**Issue by jamiesage123** [approached/laravel-image-optimizer#10]
Hello!

A user on one of my sites just tried to upload an image with a capitalized extension (for example: myprofilepicture.JPG) and the optimizeImage function threw the following exception:

'TransformHandler for file extension: "JPG" was not found'

An easy and dirty fix for this is just to add capitalized versions for each `transform_handler` in the config but obviously it would be nicer to get this fixed in this package.

Cheers.

**Comment by approached** [comment]
Hello @jamiesage123 

thank you for your issue. i have this problem fixed in version 2.2.3

https://github.com/approached/laravel-image-optimizer/tree/2.2.3
