### ISSUE TITLE
Command "/usr/bin/jpegoptim" not found.

### ISSUE THREAD

**Issue by rabb-bit** [approached/laravel-image-optimizer#11]
Hi,

I tried using the package and i'm using windows 8.1 and laravel 5.2 for my development env, and this is the error ( Command "/usr/bin/jpegoptim" not found) it showed me, can't find how to install the jpegoptim lib, is this package only for linux? please advise. 

Thanks,

**Comment by approached** [comment]
Hi @rabb-bit 

i have never tried to use it on windows machine. Maybe you need a tool like this:
https://sourceforge.net/projects/jpegoptim/

After installing you need configure the config in laravel-image-optimizer... https://github.com/approached/laravel-image-optimizer/blob/master/config/imageoptimizer.php

I hope it helps you.

**Comment by rabb-bit** [comment]
Hi @approached ,

thank you for your reply, this helps, i downloaded the jpegoptim for windows and I will try to change the configuration file. i think this will work.

Regards,
