### ISSUE TITLE
optimizeImage returns null

### ISSUE THREAD

**Issue by DaniloPolani** [approached/laravel-image-optimizer#15]
How can we use `optimizeImage()` with an existing file without using an "uploaded" one? At this time it returns null.

Otherwise it will be a good thing to use `optimizeImage` with an encoded image.

**Comment by approached** [comment]
Hi,

encoded image as a filepath or binary data?

For filepath you also use this:
https://github.com/approached/laravel-image-optimizer/blob/master/src/ImageOptimizer.php#L18

**Comment by DaniloMeritocracy** [comment]
At this time I am using filepath, but it returns null.

A good idea is to use encoded image as binary data, so we have not to save temporarily the image, optimize it and then delete.

My process is this:

1. Upload image through `$request->file()`
2. Resize image
3. Here I need to optimize it, but from step 2 I have only the possibility to retrieve the encoded value of the file or save it.
4. Upload it on S3

**Comment by approached** [comment]
@DaniloPolani 
A good idea is to use encoded image as binary data...

Feel free for a pull request 👍 

But be know, on php file uploading process, the file will automatically save under _/tmp/AD23SAD34_

**Comment by DaniloPolani** [comment]
Sure, I know it.

Anyway, how to use `optimizeImage()`? This was the original question

**Comment by approached** [comment]
Similar like this: 
https://github.com/approached/laravel-image-optimizer/blob/master/README.md#demo

Just
`
$imageOptimizer-> optimizeImage('/home/little/boy.jpg');
`

**Comment by DaniloPolani** [comment]
Ok, but if the method returns null, after `$imageOptimizer->optimizeImage()` what I have to do? Does it overwrite the image of the given filepath?

**Comment by approached** [comment]
Yes, it just overwrite.

**Comment by ctf0** [comment]
@approached we can make a middleware that check for upload file if type of image and optimize it on the fly.

@DaniloPolani for already uploaded images, u can list all files in a path and optimize them through loop.

**Comment by approached** [comment]
@ctf0 good idea :-)

**Comment by ctf0** [comment]
@approached here is the middleware https://gist.github.com/ctf0/5beee05601681309dbb9dee80ec6f84a , i didnt have a chance to test it yet so if you can do it from ur part i would appreciate it.

**Comment by approached** [comment]
It look's great 👍

**Comment by ctf0** [comment]
@approached PR sent.

**Comment by approached** [comment]
PR is merged
