### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by fujab** [approached/laravel-image-optimizer#19]
When optimizing an image, my CPU usage jumps to 100% (I'm using DigitalOcean's $5/mo plan).

Is this normal? Is there anything I can do to lower the usage other than upgrading my server?

What if I need to optimize uploaded images from 100 users at the same time?

**Comment by approached** [comment]
Hello @fujab 

try to run this commands directly on the machine, than you will see, that is normally or not.

... for example:
```
pngquant example.png

gifsicle example.gif

jpegoptim example.jpg
```

This package runs only this commands with some parameters (see config file).

**Comment by julianpring** [comment]
@approached 

I forgot my password to the account so I'm using this one. 

I just tried running `pngquant example.png` through command line, and it also spikes to 100%:

![http://i.imgur.com/9bF4TEm.png](http://i.imgur.com/9bF4TEm.png)
