### ISSUE TITLE
Why download libraries not show folder Middleware in src ???

### ISSUE THREAD

**Issue by ProjectSVN** [approached/laravel-image-optimizer#28]
Hello Mr.ctf0,approached !!!
Thanks you was support for me with libraries this. But i have one question small.
When i downloaded libraries by composer into project of me was completed but I not found folder Middleware  into vendor approached. 
I hope you will looking for it and answer for me.
Thanks

**Comment by approached** [comment]
Hi,

this is the middleware https://github.com/approached/laravel-image-optimizer/blob/master/src/Middleware/AutoImageOptimizer.php

But this function is **only now available in the master version**. I have not really tested this function yet.  In the next days i hope to create new version with this function.

Best regards

**Comment by the94air** [comment]
:+1:
