### ISSUE TITLE
Dose Not Exist

### ISSUE THREAD

**Issue by jmtittechnologies** [approached/laravel-image-optimizer#30]
ReflectionException in RouteSignatureParameters.php line 25:
Class App\Http\Controllers\ImageOptimizer does not exist
![screencapture-jmtit-app-maheshsales-com-addproduct-1499585417700](https://user-images.githubusercontent.com/29040920/27991999-982b997c-64a6-11e7-98b7-bac08b75629b.png)

**Comment by approached** [comment]
`App\Http\Controllers\ImageOptimizer` ist not a package file.
