### ISSUE TITLE
config file options are ignored

### ISSUE THREAD

**Issue by pablood85** [approached/laravel-image-optimizer#4]
Hello, I was trying to compress a jpg, but the size remained intact.
After some debugging, I found that there is no compression setted by default,  so I added a new argument in this config line:

`'jpegoptim_options' => ['--strip-all', '--all-progressive', '--max60'],`

But nothing seems to happen, the config parameters are never merged with the default ones.

Is this a known issue? 
What can I do to fix it?

Thanks

**Comment by approached** [comment]
Hi @pablood85 
i have now no time to fix it. But feel free for a pull request.

**Comment by approached** [comment]
Thank you for your contribution. I add a new version tag 2.1.0.

**Comment by Okipa** [comment]
@pablood85 This closed issue seems to be related to this one : https://github.com/approached/laravel-image-optimizer/issues/13
Any idea on how to fix this ?

**Comment by pablood85** [comment]
Sorry, I don't know how to fix that.
