### ISSUE TITLE
Not working on Laravel Homestead 

### ISSUE THREAD

**Issue by taliptako** [approached/laravel-image-optimizer#7]
I'm trying to use this on laravel homestead its not working and i'm not getting any error

**Comment by approached** [comment]
Hi,

do you have installed some convert libraries.
Like this ?
```
sudo apt-get install optipng pngquant pngcrush gifsicle jpegoptim
```

**Comment by taliptako** [comment]
Yes i installed all of them and i'm using optimizeImage instead of  optimizeUploadedImageFile.
Because i  need to optimize all images on my filesystem.

**Comment by approached** [comment]
I think that is not really clear.

optimizeImage() is just for one imagefile

but

if you have upload class like this: Symfony\Component\HttpFoundation\File\UploadedFile;
than you must use the other method.

This module currently doesn't suppert multifiles or a filepath. But feel free to implent this with a pull request.

**Comment by taliptako** [comment]
I'm using optimizeImage($filepath) like this with only one image filepath and this method should replace image in that filepath with new optimized image isnt it ?

**Comment by approached** [comment]
Yes, this image will be replaced.
