### ISSUE TITLE
Class ImageOptimizer does not exist

### ISSUE THREAD

**Issue by m-alinasab** [approached/laravel-image-optimizer#9]
after use code : 

Route::get('ttt' , function(ImageOptimizer $imageOptimizer){

        $picture = asset('s.jpg'); // image in root directory
        // optimize
        $imageOptimizer->optimizeUploadedImageFile($picture);

        // save
        Storage::put('public/ttyy.jpg', File::get($picture));

}

Error : Class ImageOptimizer does not exist

**Comment by approached** [comment]
Hi @m-alinasab ,

do you import the class? Like this:
```php
use Approached\LaravelImageOptimizer\ImageOptimizer;
```

or try this

```php
dd(app('Approached\LaravelImageOptimizer\ImageOptimizer'));
```

**Comment by m-alinasab** [comment]
Thank you for tips.

How can a picture be sent directly to the method?

for Example : 
public function opt(Request $request, ImageOptimizer $imageOptimizer)
    {
        $picture = asset('s.jpg');
        $imageOptimizer->optimizeUploadedImageFile($picture);
        Storage::put('public/newpic.jpg', File::get($picture));
    }

**Comment by approached** [comment]
I'm not sure that i have understand your question.

Use for the imageOptimizer instance like this:
```php
$imageOptimizer = app('Approached\LaravelImageOptimizer\ImageOptimizer');
```

I hope it helps you.

**Comment by m-alinasab** [comment]
i want get a picture from my Storage then optimize image and Save it again in Storage .

i dont use from form ( input file ) .

i want picture that from ago Optimize and Save it again in Storage ( replace to old file ) .

**Comment by mehranrasulian** [comment]
@m-alinasab `ImageOptimizer` accepts an instance of Symfony's UploadedFile so you may try this:

```php
$fullPathToYourFile = public_path('images/s.jpg');
$fileName = 'j.jpg'; 

$file = new Illuminate/Http/UploadedFile($fullPathToYourFile, $fileName);

$imageOptimizer->optimizeUploadedImageFile($file);

// Then store your file...

```

**Comment by approached** [comment]
@mehranrasulian thank you

or use thisfunction:
```php
public function optimizeImage($filepath, $fileExtension = null){}

...

$imageOptimizer->optimizeImage(public_path('images/s.jpg'));
```
